base_url = "https://mirkocaserta.com"
title = "Mirko Caserta"
author = "Mirko Caserta"
description = "Personal website and blog"
default_language = "en"
compile_sass = true
build_search_index = true
generate_feeds = true
theme = "modern-i18n"

taxonomies = [
    {name = "tags", paginate_by = 10},
    {name = "categories", paginate_by = 10},
]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

# Navigation menu items
[[extra.menu.main]]
name = "Blog"
url = "/"

[[extra.menu.main]]
name = "Pages"
url = "/pages/"

[[extra.menu.main]]
name = "Categories" 
url = "/categories/"

[[extra.menu.main]]
name = "Tags"
url = "/tags/"

[extra]
license = "CC BY 4.0"
license_url = "https://creativecommons.org/licenses/by/4.0/"